stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  MYSQL_DATABASE: mydatabase
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword
  MYSQL_ROOT_PASSWORD: rootpassword

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker images..."
    - docker-compose -f docker-compose.yml build
  artifacts:
    paths:
      - ./app/
      - ./docker/

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Running tests..."
    - docker-compose -f docker-compose.yml up -d
    - docker-compose exec -T web php /var/www/html/tests/run.php
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying application..."
    - docker-compose -f docker-compose.yml up -d
  only:
    - main