version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтируем init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ogtech
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
